services:
    sidus_filter.doctrine.factory.query_handler:
        class: Sidus\FilterBundle\Factory\Doctrine\DoctrineQueryHandlerFactory
        arguments:
            - '@sidus_filter.registry.filter_type'
            - '@doctrine'
        tags:
            - { name: sidus.query_handler_factory }
