services:
    sidus_filter.doctrine.filter.type.date_range:
        class: Sidus\FilterBundle\Filter\Type\Doctrine\DateRangeFilterType
        arguments:
            - date_range
            - 'Sidus\FilterBundle\Form\Type\DateRangeType'
        tags:
            - { name: sidus.filter_type }

    sidus_filter.doctrine.filter.type.text:
        class: Sidus\FilterBundle\Filter\Type\Doctrine\TextFilterType
        arguments:
            - text
            - 'Symfony\Component\Form\Extension\Core\Type\TextType'
        tags:
            - { name: sidus.filter_type }

    sidus_filter.doctrine.filter.type.choice:
        class: Sidus\FilterBundle\Filter\Type\Doctrine\ChoiceFilterType
        arguments:
            - choice
            - 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
        tags:
            - { name: sidus.filter_type }
