services:
    Sidus\FilterBundle\Filter\Type\Doctrine\DateRangeFilterType:
        public: false
        arguments:
            - date_range
            - 'Sidus\FilterBundle\Form\Type\DateRangeType'
        tags:
            - { name: sidus.filter_type }

    Sidus\FilterBundle\Filter\Type\Doctrine\TextFilterType:
        public: false
        arguments:
            - text
            - 'Symfony\Component\Form\Extension\Core\Type\TextType'
        tags:
            - { name: sidus.filter_type }

    Sidus\FilterBundle\Filter\Type\Doctrine\ChoiceFilterType:
        public: false
        arguments:
            - choice
            - 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
        tags:
            - { name: sidus.filter_type }
