parameters:
    sidus_filter.form.type.date_range.class: Sidus\FilterBundle\Form\Type\DateRangeType
    sidus_filter.form.type.order_button.class: Sidus\FilterBundle\Form\Type\OrderButtonType
    sidus_filter.form.type.sort_config.class: Sidus\FilterBundle\Form\Type\SortConfigType

services:
    sidus_filter.form.type.date_range:
        class: %sidus_filter.form.type.date_range.class%
        tags:
            - { name: form.type, alias: sidus_date_range }

    sidus_filter.form.type.order_button:
        class: %sidus_filter.form.type.order_button.class%
        tags:
            - { name: form.type, alias: sidus_order_button }

    sidus_filter.form.type.sort_config:
        class: %sidus_filter.form.type.sort_config.class%
        arguments: [%sidus_filter.filter.dto.sort_config%]
        tags:
            - { name: form.type, alias: sidus_sort_config }
