parameters:
    sidus_filter.filter.class: Sidus\FilterBundle\Filter\Filter
    sidus_filter.configuration.class: Sidus\FilterBundle\Configuration\FilterConfigurationHandler
    sidus_filter.filter_type_configuration.handler.class: Sidus\FilterBundle\Configuration\FilterTypeConfigurationHandler
    sidus_filter.filter.factory.class: Sidus\FilterBundle\Filter\FilterFactory
    sidus_filter.filter.dto.sort_config: Sidus\FilterBundle\DTO\SortConfig

services:
    sidus_filter.filter_type_configuration.handler:
        class: %sidus_filter.filter_type_configuration.handler.class%

    sidus_filter.filter.factory:
        class: %sidus_filter.filter.factory.class%
        arguments: [%sidus_filter.filter.class%, @sidus_filter.filter_type_configuration.handler]
