parameters:
    sidus_filter.filter.class: Sidus\FilterBundle\Filter\Doctrine\DoctrineFilter
    sidus_filter.configuration.class: Sidus\FilterBundle\Configuration\DoctrineFilterConfigurationHandler
    sidus_filter.filter.dto.sort_config: Sidus\FilterBundle\DTO\SortConfig

services:
    sidus_filter.filter_type_configuration.handler:
        class: Sidus\FilterBundle\Configuration\FilterTypeConfigurationHandler

    sidus_filter.filter.factory:
        class: Sidus\FilterBundle\Filter\FilterFactory
        arguments:
            - '%sidus_filter.filter.class%'
            - '@sidus_filter.filter_type_configuration.handler'
