parameters:
    sidus_filter.form.type.date_range.class: Sidus\FilterBundle\Form\Type\DateRangeType
    sidus_filter.form.type.order_button.class: Sidus\FilterBundle\Form\Type\OrderButtonType
    sidus_filter.form.type.sort_config.class: Sidus\FilterBundle\Form\Type\SortConfigType

services:
    sidus_filter.form.type.date_range:
        class: '%sidus_filter.form.type.date_range.class%'
        tags:
            - { name: form.type }

    sidus_filter.form.type.order_button:
        class: '%sidus_filter.form.type.order_button.class%'
        tags:
            - { name: form.type }

    sidus_filter.form.type.sort_config:
        class: '%sidus_filter.form.type.sort_config.class%'
        arguments: [Sidus\FilterBundle\DTO\SortConfig]
        tags:
            - { name: form.type }
